#############################################################################
# Makefile for building: benchmark_cli
# Generated by qmake (3.1) (Qt 5.15.13)
# Project:  benchmark_cli.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile benchmark_cli.pro CONFIG+=release
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -fopenmp -O2 -O3 -march=native -flto -std=gnu++1z -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = benchmark_cli1.0.0
DISTDIR = /workspace/.tmp/benchmark_cli1.0.0
LINK          = g++
LFLAGS        = -fopenmp -Wl,-O1 -flto
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt5Core.so -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = benchmark_cli.cpp \
		src/Deck.cpp \
		src/Card.cpp \
		src/GameTree.cpp \
		src/library.cpp \
		src/compairer/Dic5Compairer.cpp \
		src/nodes/ActionNode.cpp \
		src/nodes/ChanceNode.cpp \
		src/nodes/GameActions.cpp \
		src/nodes/GameTreeNode.cpp \
		src/nodes/ShowdownNode.cpp \
		src/nodes/TerminalNode.cpp \
		src/ranges/PrivateCards.cpp \
		src/ranges/PrivateCardsManager.cpp \
		src/ranges/RiverCombs.cpp \
		src/ranges/RiverRangeManager.cpp \
		src/runtime/PokerSolver.cpp \
		src/solver/BestResponse.cpp \
		src/solver/CfrSolver.cpp \
		src/solver/PCfrSolver.cpp \
		src/solver/Solver.cpp \
		src/tools/CommandLineTool.cpp \
		src/tools/GameTreeBuildingSettings.cpp \
		src/tools/lookup8.cpp \
		src/tools/PrivateRangeConverter.cpp \
		src/tools/progressbar.cpp \
		src/tools/Rule.cpp \
		src/tools/StreetSetting.cpp \
		src/tools/utils.cpp \
		src/trainable/CfrPlusTrainable.cpp \
		src/trainable/DiscountedCfrTrainable.cpp \
		src/trainable/DiscountedCfrTrainableHF.cpp \
		src/trainable/DiscountedCfrTrainableSF.cpp \
		src/trainable/Trainable.cpp \
		src/runtime/qsolverjob.cpp qrc_compairer.cpp \
		moc_qsolverjob.cpp
OBJECTS       = benchmark_cli.o \
		Deck.o \
		Card.o \
		GameTree.o \
		library.o \
		Dic5Compairer.o \
		ActionNode.o \
		ChanceNode.o \
		GameActions.o \
		GameTreeNode.o \
		ShowdownNode.o \
		TerminalNode.o \
		PrivateCards.o \
		PrivateCardsManager.o \
		RiverCombs.o \
		RiverRangeManager.o \
		PokerSolver.o \
		BestResponse.o \
		CfrSolver.o \
		PCfrSolver.o \
		Solver.o \
		CommandLineTool.o \
		GameTreeBuildingSettings.o \
		lookup8.o \
		PrivateRangeConverter.o \
		progressbar.o \
		Rule.o \
		StreetSetting.o \
		utils.o \
		CfrPlusTrainable.o \
		DiscountedCfrTrainable.o \
		DiscountedCfrTrainableHF.o \
		DiscountedCfrTrainableSF.o \
		Trainable.o \
		qsolverjob.o \
		qrc_compairer.o \
		moc_qsolverjob.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		benchmark_cli.pro include/tools/half-1-12-0.h \
		include/trainable/DiscountedCfrTrainableHF.h \
		include/trainable/DiscountedCfrTrainableSF.h \
		include/Card.h \
		include/GameTree.h \
		include/Deck.h \
		include/json.hpp \
		include/library.h \
		include/solver/PCfrSolver.h \
		include/solver/Solver.h \
		include/solver/BestResponse.h \
		include/solver/CfrSolver.h \
		include/tools/argparse.hpp \
		include/tools/CommandLineTool.h \
		include/tools/utils.h \
		include/tools/GameTreeBuildingSettings.h \
		include/tools/Rule.h \
		include/tools/StreetSetting.h \
		include/tools/lookup8.h \
		include/tools/PrivateRangeConverter.h \
		include/tools/progressbar.h \
		include/runtime/PokerSolver.h \
		include/runtime/qsolverjob.h \
		include/trainable/CfrPlusTrainable.h \
		include/trainable/DiscountedCfrTrainable.h \
		include/trainable/Trainable.h \
		include/compairer/Compairer.h \
		include/compairer/Dic5Compairer.h \
		include/nodes/ActionNode.h \
		include/nodes/ChanceNode.h \
		include/nodes/GameActions.h \
		include/nodes/GameTreeNode.h \
		include/nodes/ShowdownNode.h \
		include/nodes/TerminalNode.h \
		include/ranges/PrivateCards.h \
		include/ranges/PrivateCardsManager.h \
		include/ranges/RiverCombs.h \
		include/ranges/RiverRangeManager.h \
		include/tools/tinyformat.h \
		include/tools/qdebugstream.h benchmark_cli.cpp \
		src/Deck.cpp \
		src/Card.cpp \
		src/GameTree.cpp \
		src/library.cpp \
		src/compairer/Dic5Compairer.cpp \
		src/nodes/ActionNode.cpp \
		src/nodes/ChanceNode.cpp \
		src/nodes/GameActions.cpp \
		src/nodes/GameTreeNode.cpp \
		src/nodes/ShowdownNode.cpp \
		src/nodes/TerminalNode.cpp \
		src/ranges/PrivateCards.cpp \
		src/ranges/PrivateCardsManager.cpp \
		src/ranges/RiverCombs.cpp \
		src/ranges/RiverRangeManager.cpp \
		src/runtime/PokerSolver.cpp \
		src/solver/BestResponse.cpp \
		src/solver/CfrSolver.cpp \
		src/solver/PCfrSolver.cpp \
		src/solver/Solver.cpp \
		src/tools/CommandLineTool.cpp \
		src/tools/GameTreeBuildingSettings.cpp \
		src/tools/lookup8.cpp \
		src/tools/PrivateRangeConverter.cpp \
		src/tools/progressbar.cpp \
		src/tools/Rule.cpp \
		src/tools/StreetSetting.cpp \
		src/tools/utils.cpp \
		src/trainable/CfrPlusTrainable.cpp \
		src/trainable/DiscountedCfrTrainable.cpp \
		src/trainable/DiscountedCfrTrainableHF.cpp \
		src/trainable/DiscountedCfrTrainableSF.cpp \
		src/trainable/Trainable.cpp \
		src/runtime/qsolverjob.cpp
QMAKE_TARGET  = benchmark_cli
DESTDIR       = 
TARGET        = benchmark_cli


first: all
####### Build rules

benchmark_cli:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: benchmark_cli.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		benchmark_cli.pro \
		compairer.qrc
	$(QMAKE) -o Makefile benchmark_cli.pro CONFIG+=release
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
benchmark_cli.pro:
compairer.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile benchmark_cli.pro CONFIG+=release

qmake_all: FORCE


all: Makefile benchmark_cli

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents compairer.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents include/tools/half-1-12-0.h include/trainable/DiscountedCfrTrainableHF.h include/trainable/DiscountedCfrTrainableSF.h include/Card.h include/GameTree.h include/Deck.h include/json.hpp include/library.h include/solver/PCfrSolver.h include/solver/Solver.h include/solver/BestResponse.h include/solver/CfrSolver.h include/tools/argparse.hpp include/tools/CommandLineTool.h include/tools/utils.h include/tools/GameTreeBuildingSettings.h include/tools/Rule.h include/tools/StreetSetting.h include/tools/lookup8.h include/tools/PrivateRangeConverter.h include/tools/progressbar.h include/runtime/PokerSolver.h include/runtime/qsolverjob.h include/trainable/CfrPlusTrainable.h include/trainable/DiscountedCfrTrainable.h include/trainable/Trainable.h include/compairer/Compairer.h include/compairer/Dic5Compairer.h include/nodes/ActionNode.h include/nodes/ChanceNode.h include/nodes/GameActions.h include/nodes/GameTreeNode.h include/nodes/ShowdownNode.h include/nodes/TerminalNode.h include/ranges/PrivateCards.h include/ranges/PrivateCardsManager.h include/ranges/RiverCombs.h include/ranges/RiverRangeManager.h include/tools/tinyformat.h include/tools/qdebugstream.h $(DISTDIR)/
	$(COPY_FILE) --parents benchmark_cli.cpp src/Deck.cpp src/Card.cpp src/GameTree.cpp src/library.cpp src/compairer/Dic5Compairer.cpp src/nodes/ActionNode.cpp src/nodes/ChanceNode.cpp src/nodes/GameActions.cpp src/nodes/GameTreeNode.cpp src/nodes/ShowdownNode.cpp src/nodes/TerminalNode.cpp src/ranges/PrivateCards.cpp src/ranges/PrivateCardsManager.cpp src/ranges/RiverCombs.cpp src/ranges/RiverRangeManager.cpp src/runtime/PokerSolver.cpp src/solver/BestResponse.cpp src/solver/CfrSolver.cpp src/solver/PCfrSolver.cpp src/solver/Solver.cpp src/tools/CommandLineTool.cpp src/tools/GameTreeBuildingSettings.cpp src/tools/lookup8.cpp src/tools/PrivateRangeConverter.cpp src/tools/progressbar.cpp src/tools/Rule.cpp src/tools/StreetSetting.cpp src/tools/utils.cpp src/trainable/CfrPlusTrainable.cpp src/trainable/DiscountedCfrTrainable.cpp src/trainable/DiscountedCfrTrainableHF.cpp src/trainable/DiscountedCfrTrainableSF.cpp src/trainable/Trainable.cpp src/runtime/qsolverjob.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_compairer.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_compairer.cpp
qrc_compairer.cpp: compairer.qrc \
		/usr/lib/qt5/bin/rcc \
		resources/compairer/card5_dic_sorted.txt \
		resources/compairer/card5_dic_zipped_shortdeck.bin \
		resources/compairer/card5_dic_zipped.bin \
		resources/compairer/card5_dic_sorted_shortdeck.txt
	/usr/lib/qt5/bin/rcc -name compairer compairer.qrc -o qrc_compairer.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -fopenmp -O2 -O3 -march=native -flto -std=gnu++1z -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_qsolverjob.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_qsolverjob.cpp
moc_qsolverjob.cpp: include/runtime/qsolverjob.h \
		include/tools/qdebugstream.h \
		qstextedit.h \
		include/tools/CommandLineTool.h \
		include/runtime/PokerSolver.h \
		include/compairer/Dic5Compairer.h \
		include/compairer/Compairer.h \
		include/Card.h \
		include/tools/tinyformat.h \
		include/library.h \
		include/tools/progressbar.h \
		include/tools/PrivateRangeConverter.h \
		include/ranges/PrivateCards.h \
		include/solver/CfrSolver.h \
		include/Deck.h \
		include/ranges/RiverRangeManager.h \
		include/ranges/RiverCombs.h \
		include/ranges/PrivateCardsManager.h \
		include/trainable/CfrPlusTrainable.h \
		include/nodes/ActionNode.h \
		include/trainable/Trainable.h \
		include/json.hpp \
		include/nodes/GameTreeNode.h \
		include/nodes/GameActions.h \
		include/trainable/DiscountedCfrTrainable.h \
		include/solver/Solver.h \
		include/GameTree.h \
		include/nodes/ShowdownNode.h \
		include/nodes/TerminalNode.h \
		include/nodes/ChanceNode.h \
		include/tools/Rule.h \
		include/tools/StreetSetting.h \
		include/tools/GameTreeBuildingSettings.h \
		include/solver/PCfrSolver.h \
		include/tools/lookup8.h \
		include/tools/utils.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /workspace/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/workspace -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/13 -I/usr/include/x86_64-linux-gnu/c++/13 -I/usr/include/c++/13/backward -I/usr/lib/gcc/x86_64-linux-gnu/13/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include include/runtime/qsolverjob.h -o moc_qsolverjob.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

benchmark_cli.o: benchmark_cli.cpp include/tools/CommandLineTool.h \
		include/runtime/PokerSolver.h \
		include/compairer/Dic5Compairer.h \
		include/compairer/Compairer.h \
		include/Card.h \
		include/tools/tinyformat.h \
		include/library.h \
		include/tools/progressbar.h \
		include/tools/PrivateRangeConverter.h \
		include/ranges/PrivateCards.h \
		include/solver/CfrSolver.h \
		include/Deck.h \
		include/ranges/RiverRangeManager.h \
		include/ranges/RiverCombs.h \
		include/ranges/PrivateCardsManager.h \
		include/trainable/CfrPlusTrainable.h \
		include/nodes/ActionNode.h \
		include/trainable/Trainable.h \
		include/json.hpp \
		include/nodes/GameTreeNode.h \
		include/nodes/GameActions.h \
		include/trainable/DiscountedCfrTrainable.h \
		include/solver/Solver.h \
		include/GameTree.h \
		include/nodes/ShowdownNode.h \
		include/nodes/TerminalNode.h \
		include/nodes/ChanceNode.h \
		include/tools/Rule.h \
		include/tools/StreetSetting.h \
		include/tools/GameTreeBuildingSettings.h \
		include/solver/PCfrSolver.h \
		include/tools/lookup8.h \
		include/tools/utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o benchmark_cli.o benchmark_cli.cpp

Deck.o: src/Deck.cpp include/Deck.h \
		include/Card.h \
		include/tools/tinyformat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Deck.o src/Deck.cpp

Card.o: src/Card.cpp include/Card.h \
		include/tools/tinyformat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Card.o src/Card.cpp

GameTree.o: src/GameTree.cpp include/GameTree.h \
		include/nodes/GameTreeNode.h \
		include/tools/tinyformat.h \
		include/Deck.h \
		include/Card.h \
		include/json.hpp \
		include/nodes/ActionNode.h \
		include/trainable/Trainable.h \
		include/ranges/PrivateCards.h \
		include/nodes/GameActions.h \
		include/nodes/ShowdownNode.h \
		include/nodes/TerminalNode.h \
		include/nodes/ChanceNode.h \
		include/library.h \
		include/tools/Rule.h \
		include/tools/StreetSetting.h \
		include/tools/GameTreeBuildingSettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GameTree.o src/GameTree.cpp

library.o: src/library.cpp include/library.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o library.o src/library.cpp

Dic5Compairer.o: src/compairer/Dic5Compairer.cpp include/compairer/Dic5Compairer.h \
		include/compairer/Compairer.h \
		include/Card.h \
		include/tools/tinyformat.h \
		include/library.h \
		include/tools/progressbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Dic5Compairer.o src/compairer/Dic5Compairer.cpp

ActionNode.o: src/nodes/ActionNode.cpp include/nodes/ActionNode.h \
		include/trainable/Trainable.h \
		include/json.hpp \
		include/ranges/PrivateCards.h \
		include/Card.h \
		include/tools/tinyformat.h \
		include/nodes/GameTreeNode.h \
		include/nodes/GameActions.h \
		include/trainable/DiscountedCfrTrainable.h \
		include/trainable/DiscountedCfrTrainableHF.h \
		include/tools/half-1-12-0.h \
		include/trainable/DiscountedCfrTrainableSF.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ActionNode.o src/nodes/ActionNode.cpp

ChanceNode.o: src/nodes/ChanceNode.cpp include/nodes/ChanceNode.h \
		include/Card.h \
		include/tools/tinyformat.h \
		include/nodes/GameTreeNode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ChanceNode.o src/nodes/ChanceNode.cpp

GameActions.o: src/nodes/GameActions.cpp include/nodes/GameActions.h \
		include/tools/tinyformat.h \
		include/nodes/GameTreeNode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GameActions.o src/nodes/GameActions.cpp

GameTreeNode.o: src/nodes/GameTreeNode.cpp include/nodes/GameTreeNode.h \
		include/tools/tinyformat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GameTreeNode.o src/nodes/GameTreeNode.cpp

ShowdownNode.o: src/nodes/ShowdownNode.cpp include/nodes/ShowdownNode.h \
		include/nodes/GameTreeNode.h \
		include/tools/tinyformat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ShowdownNode.o src/nodes/ShowdownNode.cpp

TerminalNode.o: src/nodes/TerminalNode.cpp include/nodes/TerminalNode.h \
		include/nodes/GameTreeNode.h \
		include/tools/tinyformat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TerminalNode.o src/nodes/TerminalNode.cpp

PrivateCards.o: src/ranges/PrivateCards.cpp include/ranges/PrivateCards.h \
		include/Card.h \
		include/tools/tinyformat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PrivateCards.o src/ranges/PrivateCards.cpp

PrivateCardsManager.o: src/ranges/PrivateCardsManager.cpp include/ranges/PrivateCardsManager.h \
		include/ranges/PrivateCards.h \
		include/Card.h \
		include/tools/tinyformat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PrivateCardsManager.o src/ranges/PrivateCardsManager.cpp

RiverCombs.o: src/ranges/RiverCombs.cpp include/ranges/RiverCombs.h \
		include/ranges/PrivateCards.h \
		include/Card.h \
		include/tools/tinyformat.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RiverCombs.o src/ranges/RiverCombs.cpp

RiverRangeManager.o: src/ranges/RiverRangeManager.cpp include/ranges/RiverRangeManager.h \
		include/ranges/RiverCombs.h \
		include/ranges/PrivateCards.h \
		include/Card.h \
		include/tools/tinyformat.h \
		include/compairer/Compairer.h \
		include/compairer/Dic5Compairer.h \
		include/library.h \
		include/tools/progressbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RiverRangeManager.o src/ranges/RiverRangeManager.cpp

PokerSolver.o: src/runtime/PokerSolver.cpp include/runtime/PokerSolver.h \
		include/compairer/Dic5Compairer.h \
		include/compairer/Compairer.h \
		include/Card.h \
		include/tools/tinyformat.h \
		include/library.h \
		include/tools/progressbar.h \
		include/tools/PrivateRangeConverter.h \
		include/ranges/PrivateCards.h \
		include/solver/CfrSolver.h \
		include/Deck.h \
		include/ranges/RiverRangeManager.h \
		include/ranges/RiverCombs.h \
		include/ranges/PrivateCardsManager.h \
		include/trainable/CfrPlusTrainable.h \
		include/nodes/ActionNode.h \
		include/trainable/Trainable.h \
		include/json.hpp \
		include/nodes/GameTreeNode.h \
		include/nodes/GameActions.h \
		include/trainable/DiscountedCfrTrainable.h \
		include/solver/Solver.h \
		include/GameTree.h \
		include/nodes/ShowdownNode.h \
		include/nodes/TerminalNode.h \
		include/nodes/ChanceNode.h \
		include/tools/Rule.h \
		include/tools/StreetSetting.h \
		include/tools/GameTreeBuildingSettings.h \
		include/solver/PCfrSolver.h \
		include/tools/lookup8.h \
		include/tools/utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PokerSolver.o src/runtime/PokerSolver.cpp

BestResponse.o: src/solver/BestResponse.cpp include/solver/BestResponse.h \
		include/ranges/PrivateCards.h \
		include/Card.h \
		include/tools/tinyformat.h \
		include/compairer/Compairer.h \
		include/Deck.h \
		include/ranges/RiverRangeManager.h \
		include/ranges/RiverCombs.h \
		include/compairer/Dic5Compairer.h \
		include/library.h \
		include/tools/progressbar.h \
		include/ranges/PrivateCardsManager.h \
		include/trainable/CfrPlusTrainable.h \
		include/nodes/ActionNode.h \
		include/trainable/Trainable.h \
		include/json.hpp \
		include/nodes/GameTreeNode.h \
		include/nodes/GameActions.h \
		include/trainable/DiscountedCfrTrainable.h \
		include/nodes/ChanceNode.h \
		include/nodes/TerminalNode.h \
		include/nodes/ShowdownNode.h \
		include/tools/utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BestResponse.o src/solver/BestResponse.cpp

CfrSolver.o: src/solver/CfrSolver.cpp include/solver/BestResponse.h \
		include/ranges/PrivateCards.h \
		include/Card.h \
		include/tools/tinyformat.h \
		include/compairer/Compairer.h \
		include/Deck.h \
		include/ranges/RiverRangeManager.h \
		include/ranges/RiverCombs.h \
		include/compairer/Dic5Compairer.h \
		include/library.h \
		include/tools/progressbar.h \
		include/ranges/PrivateCardsManager.h \
		include/trainable/CfrPlusTrainable.h \
		include/nodes/ActionNode.h \
		include/trainable/Trainable.h \
		include/json.hpp \
		include/nodes/GameTreeNode.h \
		include/nodes/GameActions.h \
		include/trainable/DiscountedCfrTrainable.h \
		include/nodes/ChanceNode.h \
		include/nodes/TerminalNode.h \
		include/nodes/ShowdownNode.h \
		include/tools/utils.h \
		include/solver/CfrSolver.h \
		include/solver/Solver.h \
		include/GameTree.h \
		include/tools/Rule.h \
		include/tools/StreetSetting.h \
		include/tools/GameTreeBuildingSettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CfrSolver.o src/solver/CfrSolver.cpp

PCfrSolver.o: src/solver/PCfrSolver.cpp include/solver/BestResponse.h \
		include/ranges/PrivateCards.h \
		include/Card.h \
		include/tools/tinyformat.h \
		include/compairer/Compairer.h \
		include/Deck.h \
		include/ranges/RiverRangeManager.h \
		include/ranges/RiverCombs.h \
		include/compairer/Dic5Compairer.h \
		include/library.h \
		include/tools/progressbar.h \
		include/ranges/PrivateCardsManager.h \
		include/trainable/CfrPlusTrainable.h \
		include/nodes/ActionNode.h \
		include/trainable/Trainable.h \
		include/json.hpp \
		include/nodes/GameTreeNode.h \
		include/nodes/GameActions.h \
		include/trainable/DiscountedCfrTrainable.h \
		include/nodes/ChanceNode.h \
		include/nodes/TerminalNode.h \
		include/nodes/ShowdownNode.h \
		include/tools/utils.h \
		include/solver/PCfrSolver.h \
		include/solver/Solver.h \
		include/GameTree.h \
		include/tools/Rule.h \
		include/tools/StreetSetting.h \
		include/tools/GameTreeBuildingSettings.h \
		include/tools/lookup8.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PCfrSolver.o src/solver/PCfrSolver.cpp

Solver.o: src/solver/Solver.cpp include/solver/Solver.h \
		include/GameTree.h \
		include/nodes/GameTreeNode.h \
		include/tools/tinyformat.h \
		include/Deck.h \
		include/Card.h \
		include/json.hpp \
		include/nodes/ActionNode.h \
		include/trainable/Trainable.h \
		include/ranges/PrivateCards.h \
		include/nodes/GameActions.h \
		include/nodes/ShowdownNode.h \
		include/nodes/TerminalNode.h \
		include/nodes/ChanceNode.h \
		include/library.h \
		include/tools/Rule.h \
		include/tools/StreetSetting.h \
		include/tools/GameTreeBuildingSettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Solver.o src/solver/Solver.cpp

CommandLineTool.o: src/tools/CommandLineTool.cpp include/tools/CommandLineTool.h \
		include/runtime/PokerSolver.h \
		include/compairer/Dic5Compairer.h \
		include/compairer/Compairer.h \
		include/Card.h \
		include/tools/tinyformat.h \
		include/library.h \
		include/tools/progressbar.h \
		include/tools/PrivateRangeConverter.h \
		include/ranges/PrivateCards.h \
		include/solver/CfrSolver.h \
		include/Deck.h \
		include/ranges/RiverRangeManager.h \
		include/ranges/RiverCombs.h \
		include/ranges/PrivateCardsManager.h \
		include/trainable/CfrPlusTrainable.h \
		include/nodes/ActionNode.h \
		include/trainable/Trainable.h \
		include/json.hpp \
		include/nodes/GameTreeNode.h \
		include/nodes/GameActions.h \
		include/trainable/DiscountedCfrTrainable.h \
		include/solver/Solver.h \
		include/GameTree.h \
		include/nodes/ShowdownNode.h \
		include/nodes/TerminalNode.h \
		include/nodes/ChanceNode.h \
		include/tools/Rule.h \
		include/tools/StreetSetting.h \
		include/tools/GameTreeBuildingSettings.h \
		include/solver/PCfrSolver.h \
		include/tools/lookup8.h \
		include/tools/utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CommandLineTool.o src/tools/CommandLineTool.cpp

GameTreeBuildingSettings.o: src/tools/GameTreeBuildingSettings.cpp include/GameTree.h \
		include/nodes/GameTreeNode.h \
		include/tools/tinyformat.h \
		include/Deck.h \
		include/Card.h \
		include/json.hpp \
		include/nodes/ActionNode.h \
		include/trainable/Trainable.h \
		include/ranges/PrivateCards.h \
		include/nodes/GameActions.h \
		include/nodes/ShowdownNode.h \
		include/nodes/TerminalNode.h \
		include/nodes/ChanceNode.h \
		include/library.h \
		include/tools/Rule.h \
		include/tools/StreetSetting.h \
		include/tools/GameTreeBuildingSettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GameTreeBuildingSettings.o src/tools/GameTreeBuildingSettings.cpp

lookup8.o: src/tools/lookup8.cpp include/tools/lookup8.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o lookup8.o src/tools/lookup8.cpp

PrivateRangeConverter.o: src/tools/PrivateRangeConverter.cpp include/tools/PrivateRangeConverter.h \
		include/ranges/PrivateCards.h \
		include/Card.h \
		include/tools/tinyformat.h \
		include/library.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PrivateRangeConverter.o src/tools/PrivateRangeConverter.cpp

progressbar.o: src/tools/progressbar.cpp include/tools/progressbar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o progressbar.o src/tools/progressbar.cpp

Rule.o: src/tools/Rule.cpp include/tools/Rule.h \
		include/Deck.h \
		include/Card.h \
		include/tools/tinyformat.h \
		include/tools/StreetSetting.h \
		include/tools/GameTreeBuildingSettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Rule.o src/tools/Rule.cpp

StreetSetting.o: src/tools/StreetSetting.cpp include/tools/StreetSetting.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o StreetSetting.o src/tools/StreetSetting.cpp

utils.o: src/tools/utils.cpp include/tools/utils.h \
		include/ranges/PrivateCards.h \
		include/Card.h \
		include/tools/tinyformat.h \
		include/compairer/Compairer.h \
		include/Deck.h \
		include/ranges/RiverRangeManager.h \
		include/ranges/RiverCombs.h \
		include/compairer/Dic5Compairer.h \
		include/library.h \
		include/tools/progressbar.h \
		include/ranges/PrivateCardsManager.h \
		include/trainable/CfrPlusTrainable.h \
		include/nodes/ActionNode.h \
		include/trainable/Trainable.h \
		include/json.hpp \
		include/nodes/GameTreeNode.h \
		include/nodes/GameActions.h \
		include/trainable/DiscountedCfrTrainable.h \
		include/nodes/ChanceNode.h \
		include/nodes/TerminalNode.h \
		include/nodes/ShowdownNode.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o utils.o src/tools/utils.cpp

CfrPlusTrainable.o: src/trainable/CfrPlusTrainable.cpp include/trainable/CfrPlusTrainable.h \
		include/nodes/ActionNode.h \
		include/trainable/Trainable.h \
		include/json.hpp \
		include/ranges/PrivateCards.h \
		include/Card.h \
		include/tools/tinyformat.h \
		include/nodes/GameTreeNode.h \
		include/nodes/GameActions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CfrPlusTrainable.o src/trainable/CfrPlusTrainable.cpp

DiscountedCfrTrainable.o: src/trainable/DiscountedCfrTrainable.cpp include/trainable/DiscountedCfrTrainable.h \
		include/nodes/ActionNode.h \
		include/trainable/Trainable.h \
		include/json.hpp \
		include/ranges/PrivateCards.h \
		include/Card.h \
		include/tools/tinyformat.h \
		include/nodes/GameTreeNode.h \
		include/nodes/GameActions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DiscountedCfrTrainable.o src/trainable/DiscountedCfrTrainable.cpp

DiscountedCfrTrainableHF.o: src/trainable/DiscountedCfrTrainableHF.cpp include/trainable/DiscountedCfrTrainableHF.h \
		include/tools/half-1-12-0.h \
		include/nodes/ActionNode.h \
		include/trainable/Trainable.h \
		include/json.hpp \
		include/ranges/PrivateCards.h \
		include/Card.h \
		include/tools/tinyformat.h \
		include/nodes/GameTreeNode.h \
		include/nodes/GameActions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DiscountedCfrTrainableHF.o src/trainable/DiscountedCfrTrainableHF.cpp

DiscountedCfrTrainableSF.o: src/trainable/DiscountedCfrTrainableSF.cpp include/trainable/DiscountedCfrTrainableSF.h \
		include/tools/half-1-12-0.h \
		include/nodes/ActionNode.h \
		include/trainable/Trainable.h \
		include/json.hpp \
		include/ranges/PrivateCards.h \
		include/Card.h \
		include/tools/tinyformat.h \
		include/nodes/GameTreeNode.h \
		include/nodes/GameActions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DiscountedCfrTrainableSF.o src/trainable/DiscountedCfrTrainableSF.cpp

Trainable.o: src/trainable/Trainable.cpp include/trainable/Trainable.h \
		include/json.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Trainable.o src/trainable/Trainable.cpp

qsolverjob.o: src/runtime/qsolverjob.cpp include/runtime/qsolverjob.h \
		include/tools/qdebugstream.h \
		qstextedit.h \
		include/tools/CommandLineTool.h \
		include/runtime/PokerSolver.h \
		include/compairer/Dic5Compairer.h \
		include/compairer/Compairer.h \
		include/Card.h \
		include/tools/tinyformat.h \
		include/library.h \
		include/tools/progressbar.h \
		include/tools/PrivateRangeConverter.h \
		include/ranges/PrivateCards.h \
		include/solver/CfrSolver.h \
		include/Deck.h \
		include/ranges/RiverRangeManager.h \
		include/ranges/RiverCombs.h \
		include/ranges/PrivateCardsManager.h \
		include/trainable/CfrPlusTrainable.h \
		include/nodes/ActionNode.h \
		include/trainable/Trainable.h \
		include/json.hpp \
		include/nodes/GameTreeNode.h \
		include/nodes/GameActions.h \
		include/trainable/DiscountedCfrTrainable.h \
		include/solver/Solver.h \
		include/GameTree.h \
		include/nodes/ShowdownNode.h \
		include/nodes/TerminalNode.h \
		include/nodes/ChanceNode.h \
		include/tools/Rule.h \
		include/tools/StreetSetting.h \
		include/tools/GameTreeBuildingSettings.h \
		include/solver/PCfrSolver.h \
		include/tools/lookup8.h \
		include/tools/utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qsolverjob.o src/runtime/qsolverjob.cpp

qrc_compairer.o: qrc_compairer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_compairer.o qrc_compairer.cpp

moc_qsolverjob.o: moc_qsolverjob.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qsolverjob.o moc_qsolverjob.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

